language: node_js

node_js:
- "node"
- '10'
- '8'
- '6'

cache:
  yarn: true
  directories:
  - node_modules

branches:
  only:
  - master
  - "/^v\\d+\\./"

install:
- npm install

before_script:
- "npm run test"