sudo: false
language: node_js
node_js:
- '10'
- '8'
cache:
  directories:
  - "$HOME/.npm"
branches:
  only:
  - master
  - "/^v\\d+\\./"
notifications:
  slack:
    secure: SJbH7Lbx3PevksTXHbwCYLS07TXXasmxeF6qwc2kumhXQ27GlY+pJZ5np5OJaYDbDOHEOOB8I5sMfb60PeUj6N1/AHINbe4oS8OLjhwGiUe3eBfKy8msVWmGjUEnme/j/5DWddNatvny6h5uPNC6z77k4uzNCh5RhO2eJrmbhvkav8/QhtZlxnzDVZzNYzNZZCqAScIKSfl10q9sWxMH3dPmx549uh2Rz1pr+4DBlo+fu5tAz/6PvBkOa1CtmEOchF2DLuo2yiurVFKiXZkBZCq+uBU8vl1zqXmvfEtDEND76ZVymEQ5TfIZqhasHfkY9oLE73eSbrXGMbzyB0DdMaflGV9gh89ozpaemk2NXk4X12LCHdgXtMQf4w6ppSMmuncIJM/w8iYDLYaJ1mNQG7hAITQU2ed3vrNnPcfchl/D7qNPCrUtsJn0x/cQMgjw03Mn9D5v5OfcsYEyyPZMhaEuMqPHm0/F4TVZ05WUJ7z8/r7tw+b80WfoUMvmhaocsRIRwCVNg/WM5fBSheJglQ0dOh1Z9viEBBI1Rm2ICc8d17zVDQCGOe7SWK+S7JHI9JJYA2esoDUElI28XO1pmJIIqyDUO7gqkBZq0Wa8nILjuvfueNKEh89kjSpkUEhr6u6M7B9F90AKXiJiAF1oih5k7yUH2XkaZQ5fi0SVV7w=
after_success:
- npx nyc report --reporter=lcov | npx codecov
- npm run cov:check
deploy:
  skip_cleanup: true
  provider: npm
  email: andrei.moldoveanu@gmail.com
  api_key:
    secure: C+8qwAJu0nIgrZvgVvuRC3tnFFFyhp4alOQYHyjqUvE+hEV2lc+wXN3ncZKIEeD0tn6EIuIHYHQQ6H/48FhaMfpsW2SeJz5qRWsFyre79y3TfLd39ZTRFInh2QFAOk8l63EjmwV+sntC6gdgrYZhObfgEfBq7d2mmA5cx2qybRkDIQ8N6p5mm1mBRlnn3XkKUh37dooU3kQ9MutfYnKYnglKcKoYCRYk2ts6gR5c1WvWaHxle1vFZOj7qqfefLjRQb316nMfYsD4UKC9oL5BGts9I4jwsdF9VcyUM9EmN5MhGSh2nziE31xtY0h8KWC2TEuiRZXVRBraVLhNUuJy+OWkmlpIv0IK/H1KiZwNii4Ltjkow9MQtaN/8GIee+wosSPyuG76ekw/Y0VCPrRSmzZm1irdZD+v/qpu5sY7JDv5zHsOemAtC20ss0qOWlMSZzXn6Z2ZofFUp+Qb/i1zH58D31JuYUbIV6h2mdzMZNtWEmdesGYbXR0n/4RTr17WMhfW3Qh04a9esUwbDAUSSh0BEk6rGJ0d2Nn0run/eTpdM+lzTC264EvHGL4WYx8WMe4RdbRf2uq+NchmPwcpUlPrzdDQgT3T+/qjZO5llLBTRQ5256uqhXtbodm8OEmBeB5KDnDeBeCMEnPhwJzlvqzuvCRQkzg1rz54aNGZOR0=
  on:
    tags: true
    repo: Rebilly/framepay-react
