/**
 * @see https://rebilly.github.io/RebillyAPI/#operation/paymentTokenCreation
 */
type PaymentMethods =
    | 'payment-card'
    | 'ach'
    | 'bank-account'
    | 'cash'
    | 'paypal'
    | 'Alipay'
    | 'AstroPay Card'
    | 'bank-transfer'
    | 'bitcoin'
    | 'Boleto'
    | 'cash-deposit'
    | 'CASHlib'
    | 'CashToCode'
    | 'China UnionPay'
    | 'domestic-cards'
    | 'echeck'
    | 'ecoPayz'
    | 'ecoVoucher'
    | 'EPS'
    | 'ePay.bg'
    | 'Flexepin'
    | 'Giropay'
    | 'Gpaysafe'
    | 'iDebit'
    | 'iDEAL'
    | 'InstaDebit'
    | 'instant-bank-transfer'
    | 'Interac-online'
    | 'Interac-eTransfer'
    | 'invoice'
    | 'Jeton'
    | 'Klarna'
    | 'miscellaneous'
    | 'Neteller'
    | 'Nordea-Solo'
    | 'OchaPay'
    | 'online-bank-transfer'
    | 'Onlineueberweisen'
    | 'Paysafecard'
    | 'Pay4Fun'
    | 'phone'
    | 'POLi'
    | 'Przelewy24'
    | 'QQPay'
    | 'Resurs'
    | 'SEPA'
    | 'Skrill'
    | 'Skrill Rapid Transfer'
    | 'SMSVoucher'
    | 'SparkPay'
    | 'Trustly'
    | 'UPayCard'
    | 'voucher'
    | 'WeChat Pay';
