name: Build & Test

on: pull_request

jobs:
  frontend-unit-tests:
    runs-on: ubuntu-latest

    name: Run tests
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn test:unit
